name: obs_station
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # custom

  # webview
  flutter_inappwebview: ^3.4.0+2

  # state management and DI
  provider: ^4.1.3
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  flutter_mobx_helpers: ^1.0.1
  path: ^1.7.0

  # network stuff
  tcp_scanner: ^1.1.1
  connectivity: ^0.4.9
  web_socket_channel: ^1.1.0

  #security
  crypto: ^2.1.5

  #local persistant stuff
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  # after layout stuff
  after_layout: ^1.0.7+2

  # fancy done layout shit
  carousel_slider: ^2.2.1
  flutter_swiper: ^1.1.6

  # sweet icons
  font_awesome_flutter: ^8.8.1

dependency_overrides:
  path: ^1.6.4
  dartx: ^0.2.0
  characters: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: ^1.8.0
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.1.0
  # Mock for testing
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
