name: obs_blade
description: Control your OBS instance and manage your stream - live!
# Major.Minor.Patch+YYYYMMDD(XX) - XX = incrementing build (resets with new date)
version: 1.0.2+2020100801

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # CUSTOM
  # Language stuff
  intl: ^0.16.1

  # Get project meta info
  package_info: ^0.4.3

  # Webview
  flutter_inappwebview: ^4.0.0+4
  webview_flutter: ^1.0.0

  # State Management and DI
  provider: ^4.3.2+2
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  path: ^1.6.4

  # Network stuff
  tcp_scanner: ^1.1.1
  connectivity: ^0.4.9+3
  web_socket_channel: ^1.1.0

  # Security
  crypto: ^2.1.5

  # Local persistance stuff
  hive: ^1.4.4
  hive_flutter: ^0.3.1

  # To enable unique identifiable objects (models)
  uuid: ^2.2.2

  # Enable launching stuff based on URL scheme (Twitter, Browser etc.)
  url_launcher: ^5.7.2

  # See app layout on different device sizes on the fly
  device_preview: ^0.4.8

  # Fancy done layout shit
  modal_bottom_sheet: ^0.2.2
  fl_chart: ^0.11.1
  smooth_page_indicator: ^0.2.0
  keyboard_actions: ^3.3.0+1
  flutter_svg: ^0.19.0

dependency_overrides: null

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^0.39.14

  # Codegen
  build_resolvers: ^1.3.11
  build_runner: ^1.10.1
  hive_generator: ^0.7.2+1
  mobx_codegen: ^1.1.0+1

  # Mock for testing
  mockito: ^4.1.1

  # App icons
  flutter_launcher_icons: ^0.8.0

  # Splashscreen ios and android
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icons/app/app_logo_android.png'
  image_path_ios: 'assets/icons/app/app_logo_ios.png'

flutter_native_splash:
  image: assets/icons/app/splash.png
  color: '101823'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app/
    - assets/images/
    - assets/images/intro/

  fonts:
    - family: JamIcons
      fonts:
        - asset: assets/fonts/JamIcons.ttf
