name: obs_blade
description: Control your OBS instance and manage your stream - live!
# Major.Minor.Patch+YYYYMMDD(XX) - XX = incrementing build (resets with new date)
version: 2.0.0+2021120201

publish_to: 'none'

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.3

    # CUSTOM
    # Language stuff
    intl: ^0.17.0

    # Get project meta info
    package_info: ^2.0.0

    # Webview
    flutter_inappwebview: ^5.3.2

    # State Management and DI
    get_it: ^7.1.3
    mobx: ^2.0.1
    flutter_mobx: ^2.0.0
    path: ^1.8.0

    # Network stuff
    connectivity: ^3.0.2
    web_socket_channel: ^2.1.0

    # Security
    crypto: ^3.0.1

    # Local persistance stuff
    hive: ^2.0.4
    hive_flutter: ^1.1.0

    # To enable unique identifiable objects (models)
    uuid: ^3.0.5

    # Enable launching stuff based on URL scheme (Twitter, Browser etc.)
    url_launcher: ^6.0.12

    # Enable keeping the device active
    wakelock: ^0.5.6

    # Initiate native share sheet
    share_plus: ^3.0.1

    # Add custom images
    image_picker: ^0.8.4+2

    # Get various path related directories on host OS
    path_provider: ^2.0.1

    # Enable and manage in-app purchases
    in_app_purchase: ^1.0.9

    # Fancy done layout shit
    modal_bottom_sheet: ^2.0.0
    fl_chart: ^0.35.0
    smooth_page_indicator: ^0.3.0-nullsafety.0
    keyboard_actions: ^3.4.4
    expandable: ^5.0.1
    flutter_slidable: ^1.0.0-dev.9 #^0.6.0

    # Additional dependencies for packages
    xml: ^5.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^1.0.0

    # Codegen
    build_resolvers: ^2.0.0
    build_runner: ^1.12.2
    hive_generator: ^1.1.1
    mobx_codegen: ^2.0.1+2

    # Mock for testing
    mockito: ^5.0.3

    # App icons
    flutter_launcher_icons: ^0.9.1

    # Splashscreen ios and android
    flutter_native_splash: ^1.2.1

flutter_icons:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path_android: 'assets/icons/app/app_logo_android.png'
    image_path_ios: 'assets/icons/app/app_logo_ios.png'

flutter_native_splash:
    image: assets/icons/app/splash.png
    color: '101823'

flutter:
    uses-material-design: true

    assets:
        - assets/icons/app/
        - assets/images/
        - assets/images/intro/

    fonts:
        - family: JamIcons
          fonts:
              - asset: assets/fonts/JamIcons.ttf
